options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: northamerica-northeast1
  _REPO_NAME: forum-microservices

steps:

# =========================================================
# 0. ESLINT LINTING TEST
# =========================================================

- id: "Run ESLint"
  name: "node:18"
  entrypoint: bash
  args:
    - "-c"
    - |
        echo "Running ESLint..."
        npm init -y
        npm install eslint --save-dev
        # ESLint may not find a config; treat warnings only, don't fail build
        npx eslint users/*.js posts/*.js threads/*.js || echo "ESLint warnings found"
        echo "ESLint step completed"


# =========================================================
# 1. VALIDATE JSON FILES BEFORE BUILDING
# =========================================================

- id: "Validate JSON files"
  name: "node:18"
  entrypoint: bash
  args:
    - "-c"
    - |
        node -e "JSON.parse(require('fs').readFileSync('./users/db.json'))" || exit 1
        node -e "JSON.parse(require('fs').readFileSync('./posts/db.json'))" || exit 1
        node -e "JSON.parse(require('fs').readFileSync('./threads/db.json'))" || exit 1
        echo 'JSON validation passed.'


# =========================================================
# 2. BUILD DOCKER IMAGES
# =========================================================

- id: "Build posts-service"
  name: gcr.io/cloud-builders/docker
  dir: posts
  args:
    [
      "build",
      "-t", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/posts-service:$COMMIT_SHA",
      "."
    ]

- id: "Build threads-service"
  name: gcr.io/cloud-builders/docker
  dir: threads
  args:
    [
      "build",
      "-t", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/threads-service:$COMMIT_SHA",
      "."
    ]

- id: "Build users-service"
  name: gcr.io/cloud-builders/docker
  dir: users
  args:
    [
      "build",
      "-t", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/users-service:$COMMIT_SHA",
      "."
    ]


# =========================================================
# 3. TEST MICROSERVICES (PORT + SMOKE TEST)
# =========================================================

- id: "Test posts-service"
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
    - "-c"
    - |
        docker run -d --rm -p 3001:3000 --name posts-test $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/posts-service:$COMMIT_SHA
        sleep 5
        nc -z localhost 3001 || (echo "Port check FAILED for posts-service" && exit 1)
        curl -f http://localhost:3001/api/posts || (echo "Posts API FAILED" && exit 1)
        docker stop posts-test

- id: "Test threads-service"
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
    - "-c"
    - |
        docker run -d --rm -p 3002:3000 --name threads-test $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/threads-service:$COMMIT_SHA
        sleep 5
        nc -z localhost 3002 || (echo "Port check FAILED for threads-service" && exit 1)
        curl -f http://localhost:3002/api/threads || (echo "Threads API FAILED" && exit 1)
        docker stop threads-test

- id: "Test users-service"
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
    - "-c"
    - |
        docker run -d --rm -p 3003:3000 --name users-test $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/users-service:$COMMIT_SHA
        sleep 5
        nc -z localhost 3003 || (echo "Port check FAILED for users-service" && exit 1)
        curl -f http://localhost:3003/api/users || (echo "Users API FAILED" && exit 1)
        docker stop users-test


# =========================================================
# 3B. TRIVY SECURITY SCAN
# =========================================================

- id: "Trivy vulnerability scan"
  name: "aquasec/trivy:latest"
  entrypoint: "sh"
  args:
    - "-c"
    - |
        echo "Running Trivy security scans..."

        trivy image --exit-code 1 --severity HIGH,CRITICAL \
          $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/posts-service:$COMMIT_SHA || exit 1

        trivy image --exit-code 1 --severity HIGH,CRITICAL \
          $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/threads-service:$COMMIT_SHA || exit 1

        trivy image --exit-code 1 --severity HIGH,CRITICAL \
          $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/users-service:$COMMIT_SHA || exit 1

        echo "Trivy scan passed — no critical vulnerabilities found."


# =========================================================
# 4. PUSH IMAGES TO ARTIFACT REGISTRY
# =========================================================

- id: "Push posts image"
  name: gcr.io/cloud-builders/docker
  args: ["push", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/posts-service:$COMMIT_SHA"]

- id: "Push threads image"
  name: gcr.io/cloud-builders/docker
  args: ["push", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/threads-service:$COMMIT_SHA"]

- id: "Push users image"
  name: gcr.io/cloud-builders/docker
  args: ["push", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/users-service:$COMMIT_SHA"]


# =========================================================
# 5. DEPLOY EACH CLOUD RUN SERVICE
# =========================================================

- id: "Deploy posts-service"
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "run", "deploy", "posts-service",
      "--region", "$_REGION",
      "--image", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/posts-service:$COMMIT_SHA",
      "--platform", "managed",
      "--allow-unauthenticated",
      "--port=3000"
    ]

- id: "Deploy threads-service"
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "run", "deploy", "threads-service",
      "--region", "$_REGION",
      "--image", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/threads-service:$COMMIT_SHA",
      "--platform", "managed",
      "--allow-unauthenticated",
      "--port=3000"
    ]

- id: "Deploy users-service"
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "run", "deploy", "users-service",
      "--region", "$_REGION",
      "--image", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/users-service:$COMMIT_SHA",
      "--platform", "managed",
      "--allow-unauthenticated",
      "--port=3000"
    ]


images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/posts-service:$COMMIT_SHA"
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/threads-service:$COMMIT_SHA"
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/users-service:$COMMIT_SHA"
